PIXEL_PER_METER = (10.0 / 0.3) # 10 pixel 30 cm
RUN_SPEED_KMPH = 50.0 # Km / Hour
RUN_SPEED_MPM = (RUN_SPEED_KMPH * 1000.0 / 60.0)
RUN_SPEED_MPS = (RUN_SPEED_MPM / 60.0)
RUN_SPEED_PPS = (RUN_SPEED_MPS * PIXEL_PER_METER)

MIRA_RUN_SPEED_KMPH = 5.0 # Km / Hour
MIRA_RUN_SPEED_MPM = (MIRA_RUN_SPEED_KMPH * 1000.0 / 60.0)
MIRA_RUN_SPEED_MPS = (MIRA_RUN_SPEED_MPM / 60.0)
MIRA_RUN_SPEED_PPS = (MIRA_RUN_SPEED_MPS * PIXEL_PER_METER)

SNOWMAN_RUN_SPEED_KMPH = 7.0 # Km / Hour
SNOWMAN_RUN_SPEED_MPM = (SNOWMAN_RUN_SPEED_KMPH * 1000.0 / 60.0)
SNOWMAN_RUN_SPEED_MPS = (SNOWMAN_RUN_SPEED_MPM / 60.0)
SNOWMAN_RUN_SPEED_PPS = (SNOWMAN_RUN_SPEED_MPS * PIXEL_PER_METER)

TIME_PER_TIMER = 0.5
TIMER_PER_TIME = 1.0 / TIME_PER_TIMER
FRAME_PER_TIMER = 3

SPAWN_PER_TIMER = 0.6
SPAWN_PER_TIME = 1.0 / SPAWN_PER_TIMER
FRAME_PER_SPAWN = 2

TIME_PER_ACTION = 0.5
ACTION_PER_TIME = 1.0 / TIME_PER_ACTION
FRAME_PER_ACTION = 5