from pico2d import *

PIXEL_PER_METER = (10.0 / 0.3) # 10 pixel 30 cm
RUN_SPEED_KMPH = 20.0 # Km / Hour
RUN_SPEED_MPM = (RUN_SPEED_KMPH * 1000.0 / 60.0)
RUN_SPEED_MPS = (RUN_SPEED_MPM / 60.0)
RUN_SPEED_PPS = (RUN_SPEED_MPS * PIXEL_PER_METER)

ROLL_SPEED_KMPH = 60.0
ROLL_SPEED_MPM = (ROLL_SPEED_KMPH * 1000.0 / 60.0)
ROLL_SPEED_MPS = (ROLL_SPEED_MPM / 60.0)
ROLL_SPEED_PPS = (ROLL_SPEED_MPS * PIXEL_PER_METER)

JUMP_SPEED_KMPH = 60.0
JUMP_SPEED_MPM = (JUMP_SPEED_KMPH * 1000.0 / 60.0)
JUMP_SPEED_MPS = (JUMP_SPEED_MPM / 60.0)
JUMP_SPEED_PPS = (JUMP_SPEED_MPS * PIXEL_PER_METER)

TIME_PER_ACTION = 0.5
ACTION_PER_TIME = 1.0 / TIME_PER_ACTION
FRAME_PER_ACTION = 5

TIME_PER_REGEN = 0.8
REGEN_PER_TIME = 1.0 / TIME_PER_REGEN
FRAME_PER_REGEN = 40

TIME_PER_HIT = 0.5
HIT_PER_TIME = 1.0 / TIME_PER_HIT
FRAME_PER_HIT = 3

RD, LD, RU, LU, WD, WU, MD, SPACE, END, ATKED, QD, QU  = range(12)

key_event_table = {
    (SDL_KEYDOWN, SDLK_q) : QD,
    (SDL_KEYUP, SDLK_q) : QU,
    (SDL_KEYDOWN, SDLK_a) : LD,
    (SDL_KEYDOWN,SDLK_d) : RD,
    (SDL_KEYUP, SDLK_a) : LU,
    (SDL_KEYUP, SDLK_d) : RU,
    (SDL_KEYDOWN,SDLK_w) : WD,
    (SDL_KEYUP, SDLK_w) : WU,
    (SDL_KEYDOWN, SDLK_SPACE) : SPACE,
    (SDL_KEYDOWN, SDLK_j) : MD,
}
